services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gorel_escalafon
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8001:8000"
    command: sh -c "php artisan serve --host=0.0.0.0 --port=8000"
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true
